backend:
  name: github
  repo: ajwinter2022-prog/embassy-site
  branch: main
  base_url: https://embassytalent.io    # our OAuth proxy lives under /api
  auth_endpoint: /api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: site
    label: Site Content
    files:
      - file: "content/home.json"
        name: home
        label: Homepage
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: Eyebrow, name: eyebrow, widget: string }
              - { label: Headline, name: headline, widget: text }
              - { label: CTA Label, name: ctaLabel, widget: string }
              - { label: CTA Link, name: ctaHref, widget: string, default: "#contact" }
          - label: Services
            name: services
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: desc, widget: text }
              - label: Bullets
                name: bullets
                widget: list
                field: { label: Bullet, name: bullet, widget: string }
          - label: Contact
            name: contact
            widget: object
            fields:
              - { label: Email, name: email, widget: string }
              - { label: Phone, name: phone, widget: string }
              - { label: Locations, name: locations, widget: string }
